#!/usr/bin/env bash

project=$1

apps=()
while IFS="" read -r line; do
  apps+=("$line")
done < <(argocd app list -p "$project" -o name)

for app in "${apps[@]}"; do
  argocd app diff "$app" --refresh
done
