#!/usr/bin/env bash

SCRIPT_PATH=$0
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Variables which can be overridden by environment variables.
PROJECT_ROOT_DIR=${PROJECT_ROOT_DIR:-$(git rev-parse --show-toplevel)}
REMOTE_NAME=${REMOTE_NAME:-"origin"}
BRANCH_PREFIX=${BRANCH_PREFIX:-"hotfix/"}
TAG_PREFIX=${TAG_PREFIX:-"v"}
MAIN_BRANCH_NAME=${MAIN_BRANCH_NAME:-"main"}
DEVELOPMENT_BRANCH_NAME=${DEVELOPMENT_BRANCH_NAME:-"development"}

# Command line arguments.
arguments=()
TARGET_VERSION=
DEVELOPMENT_VERSION=
CONTINUE_FROM=

show_help() {
  echo "Usage: $(basename "$SCRIPT_PATH") <hotfix-version> <development-version> [options]"
  echo
  echo "Options:"
  echo "  -m, --continue-from-main         Continue from merging into main branch."
  echo "  -d, --continue-from-development  Continue from merging into development branch."
  echo "  -h, --help                       Display this help and exit."
  echo "  --                               Do not interpret any more arguments as options."
  exit 1
}

while :; do
  case $1 in
    -m|--continue-from-main)
      CONTINUE_FROM="--continue-from-main"
      ;;
    -d|--continue-from-development)
      CONTINUE_FROM="--continue-from-development"
      ;;
    -h|-\?|--help)
      show_help
      ;;
    --)
      shift
      break
      ;;
    -?*)
      echo "Error: Unknown option '$1'"
      show_help
      ;;
    ?*)
      arguments+=("$1")
      ;;
    *)
      break
  esac
  shift
done

while :; do
  case $1 in
    ?*)
      arguments+=("$1")
      ;;
    *)
      break
  esac
  shift
done

[ ${#arguments[@]} -ne 2 ] && show_help

for argument in "${arguments[@]}"; do
  if [ -z "$TARGET_VERSION" ]; then
    TARGET_VERSION=$argument
  elif [ -z "$DEVELOPMENT_VERSION" ]; then
    DEVELOPMENT_VERSION=$argument
  else
    show_help
  fi
done

source "$SCRIPT_DIR/internal"
finish "$CONTINUE_FROM"
exit $?
