#!/usr/bin/env bash

SCRIPT_PATH=$0
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Variables which can be overridden by environment variables.
PROJECT_ROOT_DIR=${PROJECT_ROOT_DIR:-$(git rev-parse --show-toplevel)}
REMOTE_NAME=${REMOTE_NAME:-"origin"}
BRANCH_PREFIX=${BRANCH_PREFIX:-"hotfix/"}
TAG_PREFIX=${TAG_PREFIX:-"v"}
BASE_BRANCH_NAME=${BASE_BRANCH_NAME:-"main"}

# Command line arguments.
arguments=()
TARGET_VERSION=

show_help() {
  echo "Usage: $(basename "$SCRIPT_PATH") <hotfix-version> [options]"
  echo
  echo "Options:"
  echo "  -h, --help  Display this help and exit."
  echo "  --          Do not interpret any more arguments as options."
  exit 1
}

while :; do
  case $1 in
    -h|-\?|--help)
      show_help
      ;;
    --)
      shift
      break
      ;;
    -?*)
      echo "Error: Unknown option '$1'"
      show_help
      ;;
    ?*)
      arguments+=("$1")
      ;;
    *)
      break
  esac
  shift
done

while :; do
  case $1 in
    ?*)
      arguments+=("$1")
      ;;
    *)
      break
  esac
  shift
done

[ ${#arguments[@]} -ne 1 ] && show_help

for argument in "${arguments[@]}"; do
  if [ -z "$TARGET_VERSION" ]; then
    TARGET_VERSION=$argument
  else
    show_help
  fi
done

source "$SCRIPT_DIR/internal"
start
exit $?
