#!/usr/bin/env bash

envFilePath="${1:-.env}"

if [ ! -f "$envFilePath" ]; then
  echo "Could not find the env file: ${envFilePath}"
  exit 1
fi

while IFS='' read -r line; do
  if [[ $line != '#'* ]] && [[ $line == *'='* ]]; then
    export "${line?}"
  fi
done < "$envFilePath"
