#!/usr/bin/env bash

SCRIPT_PATH=$0
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SCRIPT_NAME=$(basename "$SCRIPT_PATH")

source "$SCRIPT_DIR/messages"

# ------------------------------------------------------------------------------
# Parsing arguments
# ------------------------------------------------------------------------------

print_help() {
  printf "Usage: %s <release-version> [options]\n" "$SCRIPT_NAME"
  printf "\n"
  printf "Options:\n"
  printf "  -p, --project-root-dir <path>     Path to the project root directory.\n"
  printf "  -c, --change-version-path <path>  Path to the script executed when changing version.\n"
  printf "  -r, --remote-name <remote>        The name of the remote repository.\n"
  printf "  -b, --branch-prefix <prefix>      A prefix for the release branch name.\n"
  printf "  -t, --tag-prefix <prefix>         A prefix for the version tag name.\n"
  printf "  -s, --start-point <arg>           The start point of the release branch.\n"
  printf "  -y, --assume-yes                  Answer yes for all questions.\n"
  printf "  -f, --force                       Push to the remote repository forcefully.\n"
  printf "  -h, --help                        Display this help and exit.\n"
  printf "  --                                Do not interpret any more arguments as options.\n"
  exit 1
}

# Command line arguments.
arguments=()
TARGET_VERSION=
ASSUME_YES=
FORCE=

while :; do
  case $1 in
    -p|--project-root-dir)
      [ -z "$2" ] && print_missing_argument_message "$1" && print_help
      PROJECT_ROOT_DIR=$2
      shift
      ;;
    --project-root-dir=?*)
      PROJECT_ROOT_DIR=${1#*=}
      ;;
    --project-root-dir=)
      print_missing_argument_message "${1%=}" && print_help
      ;;
    -c|--change-version-path)
      [ -z "$2" ] && print_missing_argument_message "$1" && print_help
      CHANGE_VERSION_PATH=$2
      shift
      ;;
    --change-version-path=?*)
      CHANGE_VERSION_PATH=${1#*=}
      ;;
    --change-version-path=)
      print_missing_argument_message "${1%=}" && print_help
      ;;
    -r|--remote-name)
      [ -z "$2" ] && print_missing_argument_message "$1" && print_help
      REMOTE_NAME=$2
      shift
      ;;
    --remote-name=?*)
      REMOTE_NAME=${1#*=}
      ;;
    --remote-name=)
      print_missing_argument_message "${1%=}" && print_help
      ;;
    -b|--branch-prefix)
      [ -z "$2" ] && print_missing_argument_message "$1" && print_help
      BRANCH_PREFIX=$2
      shift
      ;;
    --branch-prefix=?*)
      BRANCH_PREFIX=${1#*=}
      ;;
    --branch-prefix=)
      print_missing_argument_message "${1%=}" && print_help
      ;;
    -t|--tag-prefix)
      [ -z "$2" ] && print_missing_argument_message "$1" && print_help
      TAG_PREFIX=$2
      shift
      ;;
    --tag-prefix=?*)
      TAG_PREFIX=${1#*=}
      ;;
    --tag-prefix=)
      print_missing_argument_message "${1%=}" && print_help
      ;;
    -s|--start-point)
      [ -z "$2" ] && print_missing_argument_message "$1" && print_help
      START_POINT=$2
      shift
      ;;
    --start-point=?*)
      START_POINT=${1#*=}
      ;;
    --start-point=)
      print_missing_argument_message "${1%=}" && print_help
      ;;
    -y|--assume-yes)
      ASSUME_YES=$1
      ;;
    -f|--force)
      FORCE=$1
      ;;
    -h|-\?|--help)
      print_help
      ;;
    --)
      shift
      break
      ;;
    -?*)
      print_unknown_option_message "$1" && print_help
      ;;
    ?*)
      arguments+=("$1")
      ;;
    *)
      break
  esac
  shift
done

while :; do
  case $1 in
    ?*)
      arguments+=("$1")
      ;;
    *)
      break
  esac
  shift
done

[ ${#arguments[@]} -ne 1 ] && print_help

for argument in "${arguments[@]}"; do
  if [ -z "$TARGET_VERSION" ]; then
    TARGET_VERSION=$argument
  else
    print_help
  fi
done

# Variables which can be overridden by setting options or environment variables.
PROJECT_ROOT_DIR=${PROJECT_ROOT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}
if [ -z "$CHANGE_VERSION_PATH" ]; then
  if [ -f "$PROJECT_ROOT_DIR/scripts/change_version" ]; then
    CHANGE_VERSION_PATH=$PROJECT_ROOT_DIR/scripts/change_version
  else
    CHANGE_VERSION_PATH=$SCRIPT_DIR/change_version
  fi
fi
REMOTE_NAME=${REMOTE_NAME:-"origin"}
BRANCH_PREFIX=${BRANCH_PREFIX:-"release/"}
TAG_PREFIX=${TAG_PREFIX:-"v"}
START_POINT=${START_POINT:-"$REMOTE_NAME/development"}

source "$SCRIPT_DIR/internal"
start
exit $?
